/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swalayan;

import java.awt.Font;

/**
 *
 * @author Usui Takumi
 */
public class HalamanBarang extends javax.swing.JFrame {

    /**
     * Creates new form HalamanBarang
     */
    public HalamanBarang() {
        initComponents();
        inventoryTbl.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20));
        inventoryTbl.getColumnModel().getColumn(0).setPreferredWidth(80);  //no
        inventoryTbl.getColumnModel().getColumn(1).setPreferredWidth(180); //kodebrg
        inventoryTbl.getColumnModel().getColumn(2).setPreferredWidth(220); //namabrg
        inventoryTbl.getColumnModel().getColumn(3).setPreferredWidth(116); //kategori
        inventoryTbl.getColumnModel().getColumn(4).setPreferredWidth(100); //harga
        inventoryTbl.getColumnModel().getColumn(5).setPreferredWidth(80); //jumlh
        inventoryTbl.getColumnModel().getColumn(6).setPreferredWidth(80); //ms
        inventoryTbl.getColumnModel().getColumn(7).setPreferredWidth(80); //rp
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barangBtn = new javax.swing.JButton();
        roBtn = new javax.swing.JButton();
        poBtn = new javax.swing.JButton();
        soBtn = new javax.swing.JButton();
        recommendationBtn = new javax.swing.JButton();
        barangPanel = new javax.swing.JPanel();
        cariLbl = new javax.swing.JLabel();
        cariTxt = new javax.swing.JTextField();
        logoutBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTbl = new javax.swing.JTable();
        kodebarangTxt = new javax.swing.JTextField();
        namabarangTxt = new javax.swing.JTextField();
        kategoriTxt = new javax.swing.JTextField();
        hargaTxt = new javax.swing.JTextField();
        jumlahTxt = new javax.swing.JTextField();
        msTxt = new javax.swing.JTextField();
        rpTxt = new javax.swing.JTextField();
        buatBtn = new javax.swing.JButton();
        pjLbl = new javax.swing.JLabel();
        namapjLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        barangBtn1 = new javax.swing.JButton();
        roBtn1 = new javax.swing.JButton();
        poBtn1 = new javax.swing.JButton();
        soBtn1 = new javax.swing.JButton();
        recommendationBtn1 = new javax.swing.JButton();

        barangBtn.setBackground(new java.awt.Color(80, 150, 37));
        barangBtn.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        barangBtn.setForeground(new java.awt.Color(255, 255, 255));
        barangBtn.setText("BARANG");

        roBtn.setBackground(new java.awt.Color(179, 255, 179));
        roBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        roBtn.setText("<html>REQUEST\n<p>  ORDER</htm>");
        roBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roBtnActionPerformed(evt);
            }
        });

        poBtn.setBackground(new java.awt.Color(179, 255, 179));
        poBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        poBtn.setText("<html>\nPURCHASE \n<p>ORDER\n</html>");
        poBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poBtnActionPerformed(evt);
            }
        });

        soBtn.setBackground(new java.awt.Color(179, 255, 179));
        soBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        soBtn.setText("<html>\nSTOCK <p>\nOPNAME</html>");
        soBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soBtnActionPerformed(evt);
            }
        });

        recommendationBtn.setBackground(new java.awt.Color(179, 255, 179));
        recommendationBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        recommendationBtn.setText("RECOMMENDATION");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barangPanel.setBackground(new java.awt.Color(94, 172, 46));
        barangPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cariLbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cariLbl.setForeground(new java.awt.Color(255, 255, 255));
        cariLbl.setText("Cari :");

        cariTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cariTxt.setText("Kode Barang");
        cariTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTxtActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(179, 255, 179));
        logoutBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        logoutBtn.setText("LOG OUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        inventoryTbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inventoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Barang", "Nama Barang", "Kategori", "Harga", "Jumlah", "MS", "RP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventoryTbl);

        kodebarangTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        kodebarangTxt.setText("Kode Barang");
        kodebarangTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodebarangTxtActionPerformed(evt);
            }
        });

        namabarangTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        namabarangTxt.setText("Nama Barang");

        kategoriTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        kategoriTxt.setText("Kategori");

        hargaTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        hargaTxt.setText("Harga");

        jumlahTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jumlahTxt.setText("Jumlah");

        msTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        msTxt.setText("MS");
        msTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msTxtActionPerformed(evt);
            }
        });

        rpTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        rpTxt.setText("RP");

        buatBtn.setBackground(new java.awt.Color(179, 255, 179));
        buatBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        buatBtn.setText("BUAT");

        pjLbl.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pjLbl.setForeground(new java.awt.Color(255, 255, 255));
        pjLbl.setText("Penanggung Jawab : ");

        namapjLbl.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        namapjLbl.setForeground(new java.awt.Color(255, 255, 255));
        namapjLbl.setText("namaPJ");

        javax.swing.GroupLayout barangPanelLayout = new javax.swing.GroupLayout(barangPanel);
        barangPanel.setLayout(barangPanelLayout);
        barangPanelLayout.setHorizontalGroup(
            barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangPanelLayout.createSequentialGroup()
                .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barangPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buatBtn))
                    .addGroup(barangPanelLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(barangPanelLayout.createSequentialGroup()
                                .addComponent(cariLbl)
                                .addGap(18, 18, 18)
                                .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutBtn))
                            .addGroup(barangPanelLayout.createSequentialGroup()
                                .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(barangPanelLayout.createSequentialGroup()
                                        .addComponent(pjLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(namapjLbl))
                                    .addGroup(barangPanelLayout.createSequentialGroup()
                                        .addComponent(kodebarangTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(namabarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kategoriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jumlahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(msTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        barangPanelLayout.setVerticalGroup(
            barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariLbl)
                    .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodebarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namabarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kategoriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buatBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjLbl)
                    .addComponent(namapjLbl))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(144, 216, 99));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        barangBtn1.setBackground(new java.awt.Color(80, 150, 37));
        barangBtn1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        barangBtn1.setForeground(new java.awt.Color(255, 255, 255));
        barangBtn1.setText("BARANG");
        barangBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangBtn1ActionPerformed(evt);
            }
        });

        roBtn1.setBackground(new java.awt.Color(179, 255, 179));
        roBtn1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        roBtn1.setText("<html>REQUEST\n<p>  ORDER</htm>");
        roBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roBtn1ActionPerformed(evt);
            }
        });

        poBtn1.setBackground(new java.awt.Color(179, 255, 179));
        poBtn1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        poBtn1.setText("<html>\nPURCHASE \n<p>ORDER\n</html>");

        soBtn1.setBackground(new java.awt.Color(179, 255, 179));
        soBtn1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        soBtn1.setText("<html>\nSTOCK <p>\nOPNAME</html>");
        soBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soBtn1ActionPerformed(evt);
            }
        });

        recommendationBtn1.setBackground(new java.awt.Color(179, 255, 179));
        recommendationBtn1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        recommendationBtn1.setText("RECOMMENDATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(recommendationBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soBtn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(roBtn1)
                        .addComponent(barangBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addComponent(poBtn1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(barangBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(poBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(soBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recommendationBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void kodebarangTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodebarangTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodebarangTxtActionPerformed

    private void cariTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariTxtActionPerformed

    private void msTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msTxtActionPerformed

    private void roBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roBtnActionPerformed

    private void poBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poBtnActionPerformed

    private void soBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soBtnActionPerformed

    private void barangBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barangBtn1ActionPerformed

    private void roBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roBtn1ActionPerformed

    private void soBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangBtn;
    private javax.swing.JButton barangBtn1;
    private javax.swing.JPanel barangPanel;
    private javax.swing.JButton buatBtn;
    private javax.swing.JLabel cariLbl;
    private javax.swing.JTextField cariTxt;
    private javax.swing.JTextField hargaTxt;
    private javax.swing.JTable inventoryTbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahTxt;
    private javax.swing.JTextField kategoriTxt;
    private javax.swing.JTextField kodebarangTxt;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField msTxt;
    private javax.swing.JTextField namabarangTxt;
    private javax.swing.JLabel namapjLbl;
    private javax.swing.JLabel pjLbl;
    private javax.swing.JButton poBtn;
    private javax.swing.JButton poBtn1;
    private javax.swing.JButton recommendationBtn;
    private javax.swing.JButton recommendationBtn1;
    private javax.swing.JButton roBtn;
    private javax.swing.JButton roBtn1;
    private javax.swing.JTextField rpTxt;
    private javax.swing.JButton soBtn;
    private javax.swing.JButton soBtn1;
    // End of variables declaration//GEN-END:variables
}
