/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swalayan;

import javax.swing.JOptionPane;

/**
 *
 * @author Usui Takumi
 */
public class HalamanSistemInventory extends javax.swing.JFrame {

    private SistemInventory control;
    
    /**
     * Creates new form HalamanSistemInventory
     */
    public HalamanSistemInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SistemInventoryPanel = new javax.swing.JPanel();
        barangBtn = new javax.swing.JButton();
        roBtn = new javax.swing.JButton();
        poBtn = new javax.swing.JButton();
        soBtn = new javax.swing.JButton();
        recommendationBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SistemInventoryPanel.setBackground(new java.awt.Color(144, 216, 99));
        SistemInventoryPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        barangBtn.setBackground(new java.awt.Color(179, 255, 179));
        barangBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        barangBtn.setText("BARANG");
        barangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangBtnActionPerformed(evt);
            }
        });

        roBtn.setBackground(new java.awt.Color(179, 255, 179));
        roBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        roBtn.setText("<html>REQUEST\n<p>  ORDER</htm>");
        roBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roBtnActionPerformed(evt);
            }
        });

        poBtn.setBackground(new java.awt.Color(179, 255, 179));
        poBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        poBtn.setText("<html>\nPURCHASE \n<p>ORDER\n</html>");
        poBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poBtnActionPerformed(evt);
            }
        });

        soBtn.setBackground(new java.awt.Color(179, 255, 179));
        soBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        soBtn.setText("<html>\nSTOCK <p>\nOPNAME</html>");
        soBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soBtnActionPerformed(evt);
            }
        });

        recommendationBtn.setBackground(new java.awt.Color(179, 255, 179));
        recommendationBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        recommendationBtn.setText("RECOMMENDATION");
        recommendationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommendationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SistemInventoryPanelLayout = new javax.swing.GroupLayout(SistemInventoryPanel);
        SistemInventoryPanel.setLayout(SistemInventoryPanelLayout);
        SistemInventoryPanelLayout.setHorizontalGroup(
            SistemInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemInventoryPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(SistemInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(barangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SistemInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(recommendationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roBtn)
                        .addComponent(poBtn)
                        .addComponent(soBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1046, Short.MAX_VALUE))
        );
        SistemInventoryPanelLayout.setVerticalGroup(
            SistemInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SistemInventoryPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(barangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(poBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(soBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recommendationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SistemInventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SistemInventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Maaf, fitur ini belum ditambahkan", "FITUR BELUM ADA", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_poBtnActionPerformed

    private void soBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Maaf, fitur ini belum ditambahkan", "FITUR BELUM ADA", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_soBtnActionPerformed

    private void roBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Maaf, fitur ini belum ditambahkan", "FITUR BELUM ADA", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_roBtnActionPerformed

    private void barangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangBtnActionPerformed
        control = new SistemInventory();
        
        control.menampilkanHalamanBarang();
        dispose();
    }//GEN-LAST:event_barangBtnActionPerformed

    private void recommendationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommendationBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Maaf, fitur ini belum ditambahkan", "FITUR BELUM ADA", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_recommendationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanSistemInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanSistemInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanSistemInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanSistemInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanSistemInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SistemInventoryPanel;
    private javax.swing.JButton barangBtn;
    private javax.swing.JButton poBtn;
    private javax.swing.JButton recommendationBtn;
    private javax.swing.JButton roBtn;
    private javax.swing.JButton soBtn;
    // End of variables declaration//GEN-END:variables
}
