/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swalayan;


import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usui Takumi
 */
public class HalamanBarang extends javax.swing.JFrame {

    private static String username;
    private SistemInventory control;
    private String[] title = {"Kode","NamaBRG","Kategori","Harga","Stock","MS","RP"};
    private Object data[][];
    
    /**
     * Creates new form HalamanBarang
     * @param u
     */
    public HalamanBarang(String u) {
        HalamanBarang.username = u;
        
        initComponents();        
        control = new SistemInventory(u);
        data = new Object[15][7];
        
        updateTable();
    }

    public void updateTable(){
        data = control.lihatBarang();
        inventoryTbl.setModel(new DefaultTableModel(data,title));
        inventoryTbl.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20));
        inventoryTbl.getColumnModel().getColumn(0).setPreferredWidth(100); //kodebrg
        inventoryTbl.getColumnModel().getColumn(1).setPreferredWidth(280); //namabrg
        inventoryTbl.getColumnModel().getColumn(2).setPreferredWidth(174); //kategori
        inventoryTbl.getColumnModel().getColumn(3).setPreferredWidth(140); //harga
        inventoryTbl.getColumnModel().getColumn(4).setPreferredWidth(80); //jumlh
        inventoryTbl.getColumnModel().getColumn(5).setPreferredWidth(80); //ms
        inventoryTbl.getColumnModel().getColumn(6).setPreferredWidth(80); //rp
        inventoryTbl.setRowHeight(30);
        kodebarangTxt.requestFocus();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barangPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTbl = new javax.swing.JTable();
        kodebarangTxt = new javax.swing.JTextField();
        namabarangTxt = new javax.swing.JTextField();
        kategoriTxt = new javax.swing.JTextField();
        hargaTxt = new javax.swing.JTextField();
        stockTxt = new javax.swing.JTextField();
        msTxt = new javax.swing.JTextField();
        rpTxt = new javax.swing.JTextField();
        buatBtn = new javax.swing.JButton();
        pjLbl = new javax.swing.JLabel();
        txtNamaPj = new javax.swing.JTextField();
        hapusBtn = new javax.swing.JButton();
        ubahBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        barangBtn = new javax.swing.JButton();
        roBtn = new javax.swing.JButton();
        poBtn = new javax.swing.JButton();
        soBtn = new javax.swing.JButton();
        recommendationBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barangPanel.setBackground(new java.awt.Color(94, 172, 46));
        barangPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        logoutBtn.setBackground(new java.awt.Color(179, 255, 179));
        logoutBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        logoutBtn.setText("LOG OUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        inventoryTbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        inventoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Kategori", "Harga", "Jumlah", "MS", "RP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventoryTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inventoryTbl);

        kodebarangTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        kodebarangTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodebarangTxtActionPerformed(evt);
            }
        });

        namabarangTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        kategoriTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        hargaTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        stockTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        msTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        msTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msTxtActionPerformed(evt);
            }
        });

        rpTxt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        buatBtn.setBackground(new java.awt.Color(179, 255, 179));
        buatBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        buatBtn.setText("BUAT");
        buatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatBtnActionPerformed(evt);
            }
        });

        pjLbl.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        pjLbl.setForeground(new java.awt.Color(255, 255, 255));
        pjLbl.setText("Penanggung Jawab : ");

        txtNamaPj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPjActionPerformed(evt);
            }
        });

        hapusBtn.setBackground(new java.awt.Color(179, 255, 179));
        hapusBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        hapusBtn.setText("HAPUS");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });

        ubahBtn.setBackground(new java.awt.Color(179, 255, 179));
        ubahBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ubahBtn.setText("UBAH");
        ubahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barangPanelLayout = new javax.swing.GroupLayout(barangPanel);
        barangPanel.setLayout(barangPanelLayout);
        barangPanelLayout.setHorizontalGroup(
            barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barangPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barangPanelLayout.createSequentialGroup()
                        .addComponent(kodebarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namabarangTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kategoriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(barangPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutBtn))
                    .addGroup(barangPanelLayout.createSequentialGroup()
                        .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(barangPanelLayout.createSequentialGroup()
                                .addComponent(pjLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamaPj, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(barangPanelLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(buatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ubahBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hapusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
        );
        barangPanelLayout.setVerticalGroup(
            barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBtn)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodebarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namabarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kategoriTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buatBtn)
                    .addComponent(ubahBtn)
                    .addComponent(hapusBtn))
                .addGap(18, 18, 18)
                .addGroup(barangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pjLbl)
                    .addComponent(txtNamaPj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(144, 216, 99));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        barangBtn.setBackground(new java.awt.Color(80, 150, 37));
        barangBtn.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        barangBtn.setForeground(new java.awt.Color(255, 255, 255));
        barangBtn.setText("BARANG");
        barangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangBtnActionPerformed(evt);
            }
        });

        roBtn.setBackground(new java.awt.Color(179, 255, 179));
        roBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        roBtn.setText("<html>REQUEST\n<p>  ORDER</htm>");
        roBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roBtnActionPerformed(evt);
            }
        });

        poBtn.setBackground(new java.awt.Color(179, 255, 179));
        poBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        poBtn.setText("<html>\nPURCHASE \n<p>ORDER\n</html>");
        poBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poBtnActionPerformed(evt);
            }
        });

        soBtn.setBackground(new java.awt.Color(179, 255, 179));
        soBtn.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        soBtn.setText("<html>\nSTOCK <p>\nOPNAME</html>");
        soBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soBtnActionPerformed(evt);
            }
        });

        recommendationBtn.setBackground(new java.awt.Color(179, 255, 179));
        recommendationBtn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        recommendationBtn.setText("RECOMMENDATION");
        recommendationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommendationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(recommendationBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(roBtn)
                        .addComponent(barangBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                        .addComponent(poBtn)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(barangBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(poBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(soBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recommendationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        control.menampilkanHalamanLogin();
        dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void kodebarangTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodebarangTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodebarangTxtActionPerformed

    private void msTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msTxtActionPerformed

    private void barangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barangBtnActionPerformed

    private void roBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Maaf, fitur ini belum ditambahkan", "FITUR BELUM ADA", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_roBtnActionPerformed

    private void soBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Maaf, fitur ini belum ditambahkan", "FITUR BELUM ADA", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_soBtnActionPerformed

    private void poBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Maaf, fitur ini belum ditambahkan", "FITUR BELUM ADA", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_poBtnActionPerformed

    private void recommendationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommendationBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Maaf, fitur ini belum ditambahkan", "FITUR BELUM ADA", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_recommendationBtnActionPerformed

    private void txtNamaPjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPjActionPerformed

    private void buatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatBtnActionPerformed
         control = new SistemInventory(username);
        
        String kode = kodebarangTxt.getText();
        String nama = namabarangTxt.getText();
        String kategori = kategoriTxt.getText();
        String harga = hargaTxt.getText();
        String stock = stockTxt.getText();
        String ms = msTxt.getText();
        String rp = rpTxt.getText();
        
        boolean tambah = control.tambahBarang(kode, nama, kategori, harga, stock, ms, rp);
        
        if(tambah) JOptionPane.showMessageDialog(null,"Barang dengan Kode "+kode+", Berhasil di tambahkan", "TAMBAH", JOptionPane.PLAIN_MESSAGE);
        else JOptionPane.showMessageDialog(null,"Barang dengan Kode "+kode+", Gagal di Tambahkan", "GAGAL", JOptionPane.ERROR_MESSAGE);
        
        
        updateTable();
    }//GEN-LAST:event_buatBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        control = new SistemInventory(username);
        String kode = kodebarangTxt.getText();
        
        boolean hapus = control.hapusBarang(kode);
        if(hapus) JOptionPane.showMessageDialog(null,"Barang dengan Kode "+kode+", Berhasil di hapus", "HAPUS", JOptionPane.PLAIN_MESSAGE);
        else JOptionPane.showMessageDialog(null,"Barang dengan Kode "+kode+", Gagal di hapus", "GAGAL", JOptionPane.ERROR_MESSAGE);
        
        
        updateTable();
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void ubahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahBtnActionPerformed
        control = new SistemInventory(username);
        
        String kode = kodebarangTxt.getText();
        String nama = namabarangTxt.getText();
        String kategori = kategoriTxt.getText();
        String harga = hargaTxt.getText();
        String stock = stockTxt.getText();
        String ms = msTxt.getText();
        String rp = rpTxt.getText();
        
        boolean update = control.updateBarang(kode, nama, kategori, harga, stock, ms, rp);
        
        if(update) JOptionPane.showMessageDialog(null,"Barang dengan Kode "+kode+", Berhasil di update", "UPDATE", JOptionPane.PLAIN_MESSAGE);
        else JOptionPane.showMessageDialog(null,"Barang dengan Kode "+kode+", Gagal di update", "UPDATE", JOptionPane.ERROR_MESSAGE);
        
        updateTable();
    }//GEN-LAST:event_ubahBtnActionPerformed

    private void inventoryTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTblMouseClicked
        DefaultTableModel modelTbl = (DefaultTableModel) inventoryTbl.getModel();
        int index = inventoryTbl.getSelectedRow();
        kodebarangTxt.setText(modelTbl.getValueAt(index, 0).toString());
        namabarangTxt.setText(modelTbl.getValueAt(index, 1).toString());
        kategoriTxt.setText(modelTbl.getValueAt(index, 2).toString());
        hargaTxt.setText(modelTbl.getValueAt(index, 3).toString());
        stockTxt.setText(modelTbl.getValueAt(index, 4).toString());
        msTxt.setText(modelTbl.getValueAt(index, 5).toString());
        rpTxt.setText(modelTbl.getValueAt(index, 6).toString());
    }//GEN-LAST:event_inventoryTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanBarang(username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangBtn;
    private javax.swing.JPanel barangPanel;
    private javax.swing.JButton buatBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField hargaTxt;
    private javax.swing.JTable inventoryTbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kategoriTxt;
    private javax.swing.JTextField kodebarangTxt;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField msTxt;
    private javax.swing.JTextField namabarangTxt;
    private javax.swing.JLabel pjLbl;
    private javax.swing.JButton poBtn;
    private javax.swing.JButton recommendationBtn;
    private javax.swing.JButton roBtn;
    private javax.swing.JTextField rpTxt;
    private javax.swing.JButton soBtn;
    private javax.swing.JTextField stockTxt;
    private javax.swing.JTextField txtNamaPj;
    private javax.swing.JButton ubahBtn;
    // End of variables declaration//GEN-END:variables
}
